subinclude(
    "///proto//build_defs/sdk",
)

proto_build_defs(
    name = "go_gateway",
    srcs = ["go_gateway.build_defs"],
    visibility = ["PUBLIC"],
    proto_languages = {
        "grpc_language": ["go_gateway_language"],
    }
)